require('dotenv').config();
const mongoose  = require('mongoose');
const bcrypt    = require('bcryptjs');
const Club      = require('./models/Club');
const Event     = require('./models/Event');
const BusRoute  = require('./models/BusRoute');
const Timetable = require('./models/Timetable');
const User      = require('./models/User');

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('✅ Connected to MongoDB for seeding...');

  // ── Clubs (35 real clubs from Poornima Student Council) ───────
  await Club.deleteMany({});
  const clubData = [
    { name:'Pandora Rebels',                  shortName:'Pandora',  description:'Gaming Development club focused on game design, development and esports.',           category:'Technology', icon:'🎮', captain:'Karan Pant',              viceCaptain:'Sparsh Dhamotiya',         foundedYear:'2018', members:45 },
    { name:'Hack Elite',                      shortName:'HackElite',description:'Coding & Android Club — hackathons, app development and competitive coding.',         category:'Technology', icon:'💻', captain:'Riddhi Bhatnagar',        viceCaptain:'Parth Verma',              foundedYear:'2018', members:62 },
    { name:'Udaan Aerodynamic Club',          shortName:'Udaan',    description:'Drone Club — aerodynamics, drone building, racing and aerial photography.',           category:'Technology', icon:'🚁', captain:'Aditya Kumawat',          viceCaptain:'Nakshtra Saini',           foundedYear:'2020', members:30 },
    { name:'AWS Community',                   shortName:'AWS',      description:'Amazon Web Services community — cloud computing workshops and certifications.',        category:'Technology', icon:'☁️', captain:'Aman Rawat',              viceCaptain:'Anwesha Vijay',            foundedYear:'2020', members:55 },
    { name:'MS Azure Community',              shortName:'Azure',    description:'Microsoft Azure community — cloud skills, certifications and projects.',              category:'Technology', icon:'🔷', captain:'Abufroo',                 viceCaptain:'Rehan Abuwala',            foundedYear:'2021', members:40 },
    { name:'GitHub Community',                shortName:'GitHub',   description:'Open source, version control, and collaborative coding with GitHub.',                 category:'Technology', icon:'🐙', captain:'Rudrakshi',               viceCaptain:'Madhav Porwal',            foundedYear:'2021', members:50 },
    { name:'HackerRank Community',            shortName:'HR',       description:'Competitive programming, DSA challenges and HackerRank contests.',                    category:'Technology', icon:'⭐', captain:'Divyanshi Jain',          viceCaptain:'',                         foundedYear:'2021', members:48 },
    { name:'Ethical Hacking Club',            shortName:'EHC',      description:'Cybersecurity, ethical hacking, CTF competitions and digital forensics.',             category:'Technology', icon:'🛡️', captain:'Somya Yadav',             viceCaptain:'Harshwardhan Singh',       foundedYear:'2019', members:38 },
    { name:'MLSA Club',                       shortName:'MLSA',     description:'Microsoft Learn Student Ambassadors — AI, ML and Microsoft technology learning.',     category:'Technology', icon:'🤖', captain:'Kushika Mittal',          viceCaptain:'Garima Sharma',            foundedYear:'2022', members:35 },
    { name:'Dance and Music Club',            shortName:'DMC',      description:'Classical, western, folk dance and music performances and workshops.',                 category:'Cultural',   icon:'🎵', captain:'Yati Goswami',            viceCaptain:'Anwesha Shandilya',        foundedYear:'2016', members:80 },
    { name:'Art and Design Club',             shortName:'ADC',      description:'Fine arts, digital design, illustration, painting and creative workshops.',           category:'Arts',       icon:'🎨', captain:'Anjali Gautam',           viceCaptain:'Mannat Jain',              foundedYear:'2017', members:45 },
    { name:'Literary and Theatre Club',       shortName:'LTC',      description:'Drama, theatre, creative writing, storytelling and literary events.',                 category:'Cultural',   icon:'🎭', captain:'Shreyansh Mishra',        viceCaptain:'Akshita Jha',              foundedYear:'2017', members:40 },
    { name:'Poornima Paathshala',             shortName:'Paathshala',description:'Teaching underprivileged children and social education initiatives.',                category:'Social',     icon:'📖', captain:'Khushi Kumari',           viceCaptain:'Shubham Prajapati',        foundedYear:'2018', members:60 },
    { name:'Young Indians Yuva Club',         shortName:'YI',       description:'CII Young Indians chapter — leadership, entrepreneurship and nation building.',       category:'Social',     icon:'🇮🇳', captain:'Tisha Oberoi',            viceCaptain:'',                         foundedYear:'2019', members:35 },
    { name:'Inter College Affairs Club',      shortName:'ICAC',     description:'Managing inter-college collaborations, fests, delegations and partnerships.',        category:'Academic',   icon:'🤝', captain:'Vishwash J Khandelwal',   viceCaptain:'Avni Saklecha',            foundedYear:'2019', members:30 },
    { name:'PUAS',                            shortName:'PUAS',     description:'Poornima University Astronomy Society — stargazing, astronomy and space science.',    category:'Academic',   icon:'🔭', captain:'Dakshina',                viceCaptain:'Harshita Kanwar',          foundedYear:'2020', members:25 },
    { name:'PU-Incent',                       shortName:'Incent',   description:'Entrepreneurship and startup incubation cell for student innovators.',               category:'Business',   icon:'💡', captain:'Aditya Kapoor',           viceCaptain:'Puneet K Meel',            foundedYear:'2018', members:55 },
    { name:'NSS Unit',                        shortName:'NSS',      description:'National Service Scheme — community service, camps and social responsibility.',      category:'Social',     icon:'🫱', captain:'Aditya Raj Singh Tanwar', viceCaptain:'Ujjawal Kumar Singh',      foundedYear:'2016', members:100 },
    { name:'Poornima MUN Society',            shortName:'MUN',      description:'Model United Nations — diplomacy, debate and international affairs.',                 category:'Academic',   icon:'🌍', captain:'Suhani Agarwal',          viceCaptain:'Manav Thadani',            foundedYear:'2019', members:42 },
    { name:'Debate Society',                  shortName:'Debate',   description:'Parliamentary and competitive debate, elocution and public speaking.',               category:'Academic',   icon:'🗣️', captain:'Riddhi Khunteta',         viceCaptain:'Shrey Singh Chouhan',      foundedYear:'2017', members:38 },
    { name:'वाद-संवाद संगठन',                shortName:'VadSamvad',description:'Hindi debate, poetry, and literary activities promoting Indian languages.',          category:'Cultural',   icon:'📜', captain:'Rishabh Tater',           viceCaptain:'Saksham Garg',             foundedYear:'2019', members:30 },
    { name:'Hospitality Club',                shortName:'Hosp',     description:'Event hospitality, guest management and campus ambassador activities.',               category:'Social',     icon:'🍽️', captain:'Devansu Singh',           viceCaptain:'',                         foundedYear:'2020', members:28 },
    { name:'Book Club',                       shortName:'Books',    description:'Reading, book reviews, author sessions and literary discussions.',                   category:'Academic',   icon:'📚', captain:'Shreekala Verma',         viceCaptain:'Pari Maheshwari',          foundedYear:'2020', members:32 },
    { name:'Anchoring Club',                  shortName:'Anchor',   description:'Event anchoring, hosting, voice modulation and stage presence training.',            category:'Cultural',   icon:'🎤', captain:'Shlok Gupta',             viceCaptain:'Megha Chauhan',            foundedYear:'2020', members:25 },
    { name:'Animal Welfare Club',             shortName:'AWC',      description:'Animal welfare, adoption drives, feeding programs and awareness campaigns.',         category:'Social',     icon:'🐾', captain:'Mayank Vijay',            viceCaptain:'Kanupriya Vyas',           foundedYear:'2021', members:40 },
    { name:'Disaster Risk Reduction Club',    shortName:'DRR',      description:'Disaster preparedness, risk reduction awareness and emergency response training.',   category:'Social',     icon:'🆘', captain:'Aman Pratap Singh',       viceCaptain:'Mustafa Khan Mev',         foundedYear:'2021', members:22 },
    { name:'IQAC Supporting Club',            shortName:'IQAC',     description:'Supporting Internal Quality Assurance Cell activities and accreditation.',           category:'Academic',   icon:'✅', captain:'Agni Goswami',            viceCaptain:'',                         foundedYear:'2022', members:20 },
    { name:'Photography and Videography Club',shortName:'PVC',      description:'Photography, filmmaking, video editing and visual storytelling.',                    category:'Arts',       icon:'📷', captain:'Divyansh',                viceCaptain:'Simran Sharma',            foundedYear:'2019', members:50 },
    { name:'Social Media Club',               shortName:'SMC',      description:'Managing university social media, content creation and digital marketing.',          category:'Arts',       icon:'📱', captain:'Yuvraj Singh',            viceCaptain:'Prince Agarwal',           foundedYear:'2020', members:35 },
    { name:'Podcast Club',                    shortName:'Podcast',  description:'Audio storytelling, podcast production, interviews and digital media.',              category:'Arts',       icon:'🎙️', captain:'Ankit Jangid',            viceCaptain:'Charming Khatri',          foundedYear:'2021', members:22 },
    { name:'Graphic Designing Club',          shortName:'GDC',      description:'Logo design, branding, UI/UX, poster design and digital illustration.',              category:'Arts',       icon:'🖌️', captain:'Chaitanya Solanki',       viceCaptain:'',                         foundedYear:'2020', members:38 },
    { name:'Indoor Sports Club',              shortName:'ISC',      description:'Chess, table tennis, carrom, badminton and other indoor sports tournaments.',        category:'Sports',     icon:'♟️', captain:'Pranjal Srivastava',      viceCaptain:'Yashveer Singh Shaktawat', foundedYear:'2018', members:55 },
    { name:'Outdoor Sports Club',             shortName:'OSC',      description:'Cricket, football, basketball, volleyball and outdoor athletic events.',              category:'Sports',     icon:'⚽', captain:'Bhavesh Khandelwal',      viceCaptain:'Adhyan Raj',               foundedYear:'2016', members:120 },
    { name:'Health Club',                     shortName:'Health',   description:'Fitness, yoga, mental health awareness and healthy lifestyle promotion.',            category:'Social',     icon:'💪', captain:'Raghvendra Pratap Singh', viceCaptain:'Chitransh Sharma',         foundedYear:'2021', members:45 },
    { name:'International Relation Club',     shortName:'IRC',      description:'Global affairs, cultural exchange, international student connects and diplomacy.',   category:'Academic',   icon:'🌐', captain:'Mabika Sibonelelo Jane',  viceCaptain:'Asit Charag',              foundedYear:'2022', members:28 },
  ];
  const clubs = await Club.insertMany(clubData.map(c => ({ ...c, president: c.captain, vicePresident: c.viceCaptain, isActive: true })));
  console.log(`✅ ${clubs.length} clubs seeded`);

  // Build a map of club name → _id for captain accounts
  const clubMap = {};
  clubs.forEach(c => { clubMap[c.name] = { _id: c._id, name: c.name }; });

  // ── Users ─────────────────────────────────────────────────────
  await User.deleteMany({});
  const h = (pwd) => bcrypt.hash(pwd, 12);

  const users = [
    // Student
    { name:'Rahul Sharma',              userId:'PU2021CS045',  password: await h('student123'),  role:'student',        course:'B.Tech CSE', year:'3rd Year', hostel:'Block C', room:'Room 214', isVerified:true },
    // Academic Admin
    { name:'Dr. Rajesh Kumar',          userId:'ACAD001',      password: await h('admin123'),    role:'academic_admin', department:'Computer Science',   isVerified:true },
    { name:'Mrs. Priya Verma',           userId:'HSTL001',      password: await h('admin123'),    role:'hostel_admin',   department:'Hostel Administration', isVerified:true },
    { name:'Mr. Ajay Singh',             userId:'CAMP001',      password: await h('admin123'),    role:'campus_admin',   department:'Campus Operations',    isVerified:true },
    // Laundry Admin
    { name:'Suresh Sharma',             userId:'LAUN001',      password: await h('laundry123'),  role:'laundry_admin',  department:'Laundry Services', isVerified:true },
    // Student Council — Chair
    { name:'Vanshaj Pradhan',           userId:'SC-CHAIR',     password: await h('chair123'),    role:'council_admin', isVerified:true,  councilTitle:'Chair' },
    // Student Council — Co-Chairs
    { name:'Uma Todi',                  userId:'SC-COCHAIR1',  password: await h('cochair123'),  role:'council_admin', isVerified:true,  councilTitle:'Co-Chair' },
    { name:'Aaryan Singh',              userId:'SC-COCHAIR2',  password: await h('cochair123'),  role:'council_admin', isVerified:true,  councilTitle:'Co-Chair' },
    { name:'Pranjal Yadav',             userId:'SC-COCHAIR3',  password: await h('cochair123'),  role:'council_admin', isVerified:true,  councilTitle:'Co-Chair' },
    // Club Captains
    { name:'Karan Pant',                userId:'CAP-PANDORA',  password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['Pandora Rebels']._id,                   clubName:'Pandora Rebels' },
    { name:'Riddhi Bhatnagar',          userId:'CAP-HACKELITE',password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['Hack Elite']._id,                       clubName:'Hack Elite' },
    { name:'Aditya Kumawat',            userId:'CAP-UDAAN',    password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['Udaan Aerodynamic Club']._id,            clubName:'Udaan Aerodynamic Club' },
    { name:'Aman Rawat',                userId:'CAP-AWS',      password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['AWS Community']._id,                     clubName:'AWS Community' },
    { name:'Abufroo',                   userId:'CAP-AZURE',    password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['MS Azure Community']._id,                clubName:'MS Azure Community' },
    { name:'Rudrakshi',                 userId:'CAP-GITHUB',   password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['GitHub Community']._id,                  clubName:'GitHub Community' },
    { name:'Divyanshi Jain',            userId:'CAP-HR',       password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['HackerRank Community']._id,              clubName:'HackerRank Community' },
    { name:'Somya Yadav',               userId:'CAP-EHC',      password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['Ethical Hacking Club']._id,              clubName:'Ethical Hacking Club' },
    { name:'Kushika Mittal',            userId:'CAP-MLSA',     password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['MLSA Club']._id,                         clubName:'MLSA Club' },
    { name:'Yati Goswami',              userId:'CAP-DANCE',    password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['Dance and Music Club']._id,              clubName:'Dance and Music Club' },
    { name:'Anjali Gautam',             userId:'CAP-ART',      password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['Art and Design Club']._id,               clubName:'Art and Design Club' },
    { name:'Shreyansh Mishra',          userId:'CAP-LTC',      password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['Literary and Theatre Club']._id,         clubName:'Literary and Theatre Club' },
    { name:'Khushi Kumari',             userId:'CAP-PAATH',    password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['Poornima Paathshala']._id,               clubName:'Poornima Paathshala' },
    { name:'Tisha Oberoi',              userId:'CAP-YI',       password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['Young Indians Yuva Club']._id,           clubName:'Young Indians Yuva Club' },
    { name:'Vishwash J Khandelwal',     userId:'CAP-ICAC',     password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['Inter College Affairs Club']._id,        clubName:'Inter College Affairs Club' },
    { name:'Dakshina',                  userId:'CAP-PUAS',     password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['PUAS']._id,                              clubName:'PUAS' },
    { name:'Aditya Kapoor',             userId:'CAP-INCENT',   password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['PU-Incent']._id,                         clubName:'PU-Incent' },
    { name:'Aditya Raj Singh Tanwar',   userId:'CAP-NSS',      password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['NSS Unit']._id,                          clubName:'NSS Unit' },
    { name:'Suhani Agarwal',            userId:'CAP-MUN',      password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['Poornima MUN Society']._id,              clubName:'Poornima MUN Society' },
    { name:'Riddhi Khunteta',           userId:'CAP-DEBATE',   password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['Debate Society']._id,                    clubName:'Debate Society' },
    { name:'Rishabh Tater',             userId:'CAP-VAD',      password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['वाद-संवाद संगठन']._id,                  clubName:'वाद-संवाद संगठन' },
    { name:'Devansu Singh',             userId:'CAP-HOSP',     password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['Hospitality Club']._id,                  clubName:'Hospitality Club' },
    { name:'Shreekala Verma',           userId:'CAP-BOOK',     password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['Book Club']._id,                         clubName:'Book Club' },
    { name:'Shlok Gupta',               userId:'CAP-ANCHOR',   password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['Anchoring Club']._id,                    clubName:'Anchoring Club' },
    { name:'Mayank Vijay',              userId:'CAP-AWC',      password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['Animal Welfare Club']._id,               clubName:'Animal Welfare Club' },
    { name:'Aman Pratap Singh',         userId:'CAP-DRR',      password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['Disaster Risk Reduction Club']._id,      clubName:'Disaster Risk Reduction Club' },
    { name:'Agni Goswami',              userId:'CAP-IQAC',     password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['IQAC Supporting Club']._id,              clubName:'IQAC Supporting Club' },
    { name:'Divyansh',                  userId:'CAP-PVC',      password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['Photography and Videography Club']._id,  clubName:'Photography and Videography Club' },
    { name:'Yuvraj Singh',              userId:'CAP-SMC',      password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['Social Media Club']._id,                 clubName:'Social Media Club' },
    { name:'Ankit Jangid',              userId:'CAP-PODCAST',  password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['Podcast Club']._id,                      clubName:'Podcast Club' },
    { name:'Chaitanya Solanki',         userId:'CAP-GDC',      password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['Graphic Designing Club']._id,            clubName:'Graphic Designing Club' },
    { name:'Pranjal Srivastava',        userId:'CAP-ISC',      password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['Indoor Sports Club']._id,                clubName:'Indoor Sports Club' },
    { name:'Bhavesh Khandelwal',        userId:'CAP-OSC',      password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['Outdoor Sports Club']._id,               clubName:'Outdoor Sports Club' },
    { name:'Raghvendra Pratap Singh',   userId:'CAP-HEALTH',   password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['Health Club']._id,                       clubName:'Health Club' },
    { name:'Mabika Sibonelelo Jane',    userId:'CAP-IRC',      password: await h('captain123'),  role:'club_captain', isVerified:true, clubId: clubMap['International Relation Club']._id,       clubName:'International Relation Club' },

    // Vice Captains (sample - same access as captain for their club)
    { name:'Sparsh Dhamotiya',            userId:'VC-PANDORA',   password: await h('captain123'),  role:'vice_captain', isVerified:true, clubId: clubMap['Pandora Rebels']._id,                   clubName:'Pandora Rebels' },
    { name:'Parth Verma',                 userId:'VC-HACKELITE', password: await h('captain123'),  role:'vice_captain', isVerified:true, clubId: clubMap['Hack Elite']._id,                       clubName:'Hack Elite' },
    { name:'Ujjawal Kumar Singh',         userId:'VC-NSS',       password: await h('captain123'),  role:'vice_captain', isVerified:true, clubId: clubMap['NSS Unit']._id,                          clubName:'NSS Unit' },
  ];
  await User.insertMany(users);
  console.log(`✅ ${users.length} user accounts created`);

  // ── Events ────────────────────────────────────────────────────
  await Event.deleteMany({});
  const now = new Date();
  await Event.insertMany([
    { title:'Lakshya — Annual Flagship Fest 2025',    description:'The biggest annual fest of Poornima University organized by the Student Council.',                   date: new Date(now.getFullYear(), now.getMonth(), now.getDate()+25), time:'10:00 AM', venue:'University Main Ground',    type:'cultural', isOngoing:false, createdBy:'Student Council' },
    { title:'Mid-Semester Examinations',              description:'Mid-sem exams for all B.Tech & MBA students.',                                                        date: new Date(now.getFullYear(), now.getMonth(), now.getDate()+5),  time:'09:00 AM', venue:'Examination Hall A, B, C',   type:'exam',     isOngoing:true,  createdBy:'Academic Admin' },
    { title:'Hackathon 2.0 — 24hr Coding Marathon',  description:'Organized by Hack Elite Club. Open to all branches.',                                                 date: new Date(now.getFullYear(), now.getMonth(), now.getDate()+8),  time:'10:00 AM', venue:'Computer Lab Block A',       type:'club',     clubName:'Hack Elite', isOngoing:true, createdBy:'Academic Admin' },
    { title:'CTF Cybersecurity Challenge',            description:'Capture The Flag competition organized by Ethical Hacking Club.',                                     date: new Date(now.getFullYear(), now.getMonth(), now.getDate()+3),  time:'11:00 AM', venue:'Network Lab, Block B',       type:'club',     clubName:'Ethical Hacking Club', isOngoing:true, createdBy:'Academic Admin' },
    { title:'Annual Sports Meet 2025',               description:'Inter-hostel cricket, basketball and athletics championship by Outdoor Sports Club.',                 date: new Date(now.getFullYear(), now.getMonth(), now.getDate()+12), time:'07:00 AM', venue:'University Sports Ground',   type:'sports',   clubName:'Outdoor Sports Club', isOngoing:true, createdBy:'Academic Admin' },
    { title:'MUN Conference 2025',                   description:'Model United Nations conference organized by Poornima MUN Society.',                                   date: new Date(now.getFullYear(), now.getMonth(), now.getDate()+15), time:'09:00 AM', venue:'Seminar Hall 1 & 2',         type:'club',     clubName:'Poornima MUN Society', isOngoing:false, createdBy:'Academic Admin' },
    { title:'Guest Lecture: AI & Future of Work',    description:'Industry expert talk on artificial intelligence and career opportunities.',                             date: new Date(now.getFullYear(), now.getMonth(), now.getDate()+7),  time:'02:00 PM', venue:'Seminar Hall 1',             type:'academic', isOngoing:false, createdBy:'Academic Admin' },
  ]);
  console.log('✅ Events seeded');

  // ── Bus Routes ────────────────────────────────────────────────
  await BusRoute.deleteMany({});

  // ── REAL Poornima University Bus Routes (from official website) ────────────
  // Transport Officer: Vishnu Kumar Yadav | 9829855516
  // Fleet: 8 Tata buses + 36 Swaraj buses + 2 Electric Carts
  // All buses reach Poornima University by 8:20 AM | Return: 5:30 PM

  await BusRoute.insertMany([
    {
      routeNo: 'R-01',
      routeName: 'Jagatpura & Vatika Road – Poornima University',
      annualFee: 20000,
      morning: '07:00 AM', evening: '05:30 PM',
      driver: 'Vishnu Kumar Yadav (Transport Officer)', driverPhone: '9829855516',
      vehicle: 'Poornima University Bus',
      stops: [
        {name:'Bheruji Circle',               landmark:'No. 25'},
        {name:'Pratap Nagar Sec. No.11-30',   landmark:'No. 30'},
        {name:'Kalimata Mandir (Haldi Ghati Marg)', landmark:'No. 45'},
        {name:'Panna Dhay Circle',            landmark:'No. 55'},
        {name:'Bus Stand No. 6 (Haldi Ghati Marg)', landmark:'No. 60'},
        {name:'Mausam Vibhag (Near IIHMR)',   landmark:'No. 65'},
        {name:'Cheelgadi Restaurant',         landmark:'No. 67'},
        {name:'Maharana Pratap Circle',       landmark:'No. 70'},
        {name:'Raj Aangan Club',              landmark:'No. 75'},
        {name:'Akshaypatra',                  landmark:'No. 85'},
        {name:'Dwarika Apartment Circle',     landmark:'No. 93'},
        {name:'NRI Circle',                   landmark:'No. 97'},
        {name:'NRI Ka Chauraha (Jagatpura Road)', landmark:'No. 285'},
        {name:'India Gate',                   landmark:'No. 101'},
        {name:'Kumbha Gate',                  landmark:'No. 103'},
        {name:'LIC Office',                   landmark:'No. 105'},
        {name:'Pratap Plaza',                 landmark:'No. 109'},
        {name:'7 No. Bus Stand (Jagatpura)',  landmark:'No. 277'},
        {name:'Laxmi Sweets',                 landmark:'No. 111'},
        {name:'Gaushala',                     landmark:'No. 113'},
        {name:'Choudhary Petrol Pump',        landmark:'No. 114'},
        {name:'Sanganer Thana',               landmark:'No. 115'},
        {name:'Sitabari',                     landmark:'No. 117'},
        {name:'Taron Ki Koont',               landmark:'No. 121'},
        {name:'Chouradiya Petrol Pump',       landmark:'No. 303'},
        {name:'SKIT Jagatpura',               landmark:'No. 280'},
        {name:'Mahima Panorama (Jagatpura)',  landmark:'No. 281'},
        {name:'D-Mart (Kendriya Vihar Road)', landmark:'No. 279'},
        {name:'Balaji Mandir (Vatika Road)',  landmark:'No. 11'},
        {name:'Shivdaspura',                  landmark:'No. 7'},
        {name:'Gulmohar Garden (Vatika Road)',landmark:'No. 99'},
        {name:'Meena Chauk (Vatika Road)',    landmark:'No. 100'},
        {name:'Ring Road (Vatika Road)',      landmark:'No. 102'},
        {name:'Poornima University',          landmark:'Main Gate'},
      ]
    },
    {
      routeNo: 'R-02',
      routeName: 'Mansarovar & Malviya Nagar – Poornima University',
      annualFee: 30000,
      morning: '06:50 AM', evening: '05:30 PM',
      driver: 'Vishnu Kumar Yadav (Transport Officer)', driverPhone: '9829855516',
      vehicle: 'Poornima University Bus',
      stops: [
        {name:'Chaksu',                       landmark:'No. 5'},
        {name:'CBI Phatak Jagatpura',         landmark:'No. 276'},
        {name:'Kundanpura Phatak (Indra Gandhi Nagar)', landmark:'No. 278'},
        {name:'Durgapura Bus Stand',          landmark:'No. 125'},
        {name:'Jaipur Hospital',              landmark:'No. 129'},
        {name:'Jawahar Circle',               landmark:'No. 201'},
        {name:'Gold Souk',                    landmark:'No. 204'},
        {name:'Delhi ByPass-Getor Mode',      landmark:'No. 206'},
        {name:'Balaji Mode',                  landmark:'No. 211'},
        {name:'Apex Circle',                  landmark:'No. 215'},
        {name:'Kailgiri Hospital',            landmark:'No. 218'},
        {name:'Hari Marg',                    landmark:'No. 220'},
        {name:'St. Anselm School',            landmark:'No. 222'},
        {name:'Jain Mandir, Sec.3 (Malviya Nagar)', landmark:'No. 223'},
        {name:'Rungta Hospital',              landmark:'No. 225'},
        {name:'Dana Pani (Malviya Nagar)',    landmark:'No. 228'},
        {name:'Govind Marg',                  landmark:'No. 230'},
        {name:'Sec. 04 & 06 Main Road (Malviya Nagar)', landmark:'No. 232'},
        {name:'Reliance Fresh (Malviya Nagar)',landmark:'No. 234'},
        {name:'Model Town (Shree Hospital)',  landmark:'No. 271'},
        {name:'Jagatpura Flyover',            landmark:'No. 275'},
        {name:'Jain Mandir (Mahaveer Nagar)', landmark:'No. 401'},
        {name:'Durga Mandir (Mahaveer Nagar)',landmark:'No. 403'},
        {name:'Maharani Farm',                landmark:'No. 408'},
        {name:'Gangotri Rly. Station',        landmark:'No. 413'},
        {name:'Gourav Tower',                 landmark:'No. 503'},
        {name:'MNIT',                         landmark:'No. 508'},
        {name:'K.V. No.-3',                   landmark:'No. 509'},
        {name:'RTO Circle (Jhalana Dungari)', landmark:'No. 510'},
        {name:'Krishi Karyalaya',             landmark:'No. 123'},
        {name:'Kamal & Company',              landmark:'No. 133'},
        {name:'Gatta',                        landmark:'No. 135'},
        {name:'Laxmi Mandir Circle (Tonk Road)', landmark:'No. 137'},
        {name:'Mansarovar Puliya',            landmark:'No. 305'},
        {name:'Mansarovar Sec. 6',            landmark:'No. 307'},
        {name:'Rajawat Farm',                 landmark:'No. 309'},
        {name:'SFS Hospital',                 landmark:'No. 314'},
        {name:'IS-322'},
        {name:'Vijay Path'},
        {name:'Kesar Chauraha',               landmark:'No. 328'},
        {name:'Jodhpur Sweets (Mansarovar)',  landmark:'No. 330'},
        {name:'Thadi Market',                 landmark:'No. 335'},
        {name:'Patel Marg',                   landmark:'No. 338'},
        {name:'Ramtirth Marg',                landmark:'No. 341'},
        {name:'KV No. 05',                    landmark:'No. 351'},
        {name:'Sharyu Marg',                  landmark:'No. 354'},
        {name:'VT Road',                      landmark:'No. 357'},
        {name:'Hira Path',                    landmark:'No. 360'},
        {name:'Rajat Path',                   landmark:'No. 363'},
        {name:'Kiran Path',                   landmark:'No. 365'},
        {name:'Varun Path',                   landmark:'No. 367'},
        {name:'Swaran Path',                  landmark:'No. 369'},
        {name:'Kaveri Path',                  landmark:'No. 371'},
        {name:'Stadium (Mansarover)',         landmark:'No. 373'},
        {name:'Muhana Mandi Gate No. 01',     landmark:'No. 380'},
        {name:'Muhana Mandi Gate No. 03',     landmark:'No. 379'},
        {name:'Hyatt Hotel',                  landmark:'No. 378'},
        {name:'Patrakar Colony',              landmark:'No. 374'},
        {name:'Vande Mataram Circle (Mahima Apartment)', landmark:'No. 377'},
        {name:'Ashwani Hospital (Manyawas Road)', landmark:'No. 376'},
        {name:'Maharani Garden',              landmark:'No. 375'},
        {name:'Triveni Nagar Circle',         landmark:'No. 417'},
        {name:'Gopalpura Police Chouki',      landmark:'No. 418'},
        {name:'Tempo Stand',                  landmark:'No. 421'},
        {name:'Mahesh Nagar Chauraha',        landmark:'No. 424'},
        {name:'Arjun Nagar Phatak',           landmark:'No. 426'},
        {name:'Mahesh Nagar Phatak',          landmark:'No. 428'},
        {name:'Ridhi-Sidhi',                  landmark:'No. 431'},
        {name:'Narayan Niwas',                landmark:'No. 433'},
        {name:'Nehru Palace',                 landmark:'No. 139'},
        {name:'Gandhi Nagar Mode',            landmark:'No. 141'},
        {name:'Sodhani Sweets (Tonk Road)',   landmark:'No. 143'},
        {name:'Rambagh Circle',               landmark:'No. 145'},
        {name:'OTS Chauraha (JLN Marg)',      landmark:'No. 511'},
        {name:'Bajaj Nagar Tiraha',           landmark:'No. 514'},
        {name:'Gandhi Circle',                landmark:'No. 516'},
        {name:'Commerce College',             landmark:'No. 518'},
        {name:'Rajasthan College',            landmark:'No. 520'},
        {name:'Rajasthan University',         landmark:'No. 523'},
        {name:'Birla Mandir',                 landmark:'No. 526'},
        {name:'JP Phatak',                    landmark:'No. 801'},
        {name:'Imli Phatak',                  landmark:'No. 805'},
        {name:'Poornima University',          landmark:'Main Gate'},
      ]
    },
    {
      routeNo: 'R-03',
      routeName: 'SMS Hospital, Khatipura & Niwaru Road – Poornima University',
      annualFee: 35000,
      morning: '06:30 AM', evening: '05:30 PM',
      driver: 'Vishnu Kumar Yadav (Transport Officer)', driverPhone: '9829855516',
      vehicle: 'Poornima University Bus',
      stops: [
        {name:'SMS Hospital',                     landmark:'No. 153'},
        {name:'Maharaja College',                 landmark:'No. 155'},
        {name:'Ajmeri Gate',                      landmark:'No. 157'},
        {name:'Sanganeri Gate',                   landmark:'No. 163'},
        {name:'Ghat Gate',                        landmark:'No. 166'},
        {name:'Transport Nagar',                  landmark:'No. 170'},
        {name:'Kisan Dharam Kanta (Mansarovar)',  landmark:'No. 372'},
        {name:'Gurjar ki Thadi',                  landmark:'No. 435'},
        {name:'80 Feet Mahesh Nagar',             landmark:'No. 437'},
        {name:'Ganga Jamuna Petrol Pump',         landmark:'No. 439'},
        {name:'Devi Nagar',                       landmark:'No. 441'},
        {name:'Sanjeevani Hospital',              landmark:'No. 443'},
        {name:'Lazeez Hotel',                     landmark:'No. 445'},
        {name:'Dana Pani (Shyam Nagar)',          landmark:'No. 448'},
        {name:'Somani Hospital',                  landmark:'No. 450'},
        {name:'Gautam Marg (Nirman Nagar)',       landmark:'No. 452'},
        {name:'Vijay Path Circle (Tilak Nagar)',  landmark:'No. 528'},
        {name:'Pani Ki Tanki (Tilak Nagar)',      landmark:'No. 530'},
        {name:'Jawahar Nagar (Tuti Puliya)',      landmark:'No. 532'},
        {name:'Jawahar Nagar Dairy (MPS)',        landmark:'No. 535'},
        {name:'Parnami Mandir',                   landmark:'No. 543'},
        {name:'Mama Ka Hotel',                    landmark:'No. 548'},
        {name:'Barf Khana',                       landmark:'No. 551'},
        {name:'Sindhi Colony (Raja Park)',        landmark:'No. 553'},
        {name:'Mental Hospital',                  landmark:'No. 555'},
        {name:'Kishor Karagarh',                  landmark:'No. 557'},
        {name:'Dharam Singh Circle',              landmark:'No. 560'},
        {name:'Bhagat Singh Park',                landmark:'No. 561'},
        {name:'Govt. Press Circle',               landmark:'No. 812'},
        {name:'Govt. Hostel',                     landmark:'No. 815'},
        {name:'Khasa Koti Circle',                landmark:'No. 820'},
        {name:'Pital Factory',                    landmark:'No. 824'},
        {name:'Dudh Mandi',                       landmark:'No. 826'},
        {name:'Collectorate Circle',              landmark:'No. 823'},
        {name:'Chinkara Canteen',                 landmark:'No. 825'},
        {name:'Power House (Hawa Sadak)',         landmark:'No. 828'},
        {name:'Ram Mandir (Hawa Sadak)',          landmark:'No. 901'},
        {name:'Nandpuri (Hawa Sadak)',            landmark:'No. 905'},
        {name:'Ram Nagar',                        landmark:'No. 909'},
        {name:'Sushilpura',                       landmark:'No. 912'},
        {name:'Sodala Thana',                     landmark:'No. 915'},
        {name:'NBC',                              landmark:'No. 916'},
        {name:'Galta Gate',                       landmark:'No. 171'},
        {name:'Khole Ke Hanuman Ji',              landmark:'No. 172'},
        {name:'Purani Chungi (Delhi ByePass)',    landmark:'No. 173'},
        {name:'Prem Nagar Puliya (Agra Road)',    landmark:'No. 174'},
        {name:'Purani Chungi (Agra Road)',        landmark:'No. 178'},
        {name:'Tilak Hospital (Agra Road)',       landmark:'No. 182'},
        {name:'Rajesh Coach (Agra Road)',         landmark:'No. 183'},
        {name:'52 Feet Hanuman Ji',               landmark:'No. 181'},
        {name:'Kanota Thana',                     landmark:'No. 184'},
        {name:'Mali Ki Khoti',                    landmark:'No. 175'},
        {name:'Ram Garh Mode',                    landmark:'No. 176'},
        {name:'Kunda Petrol Pump (Delhi Road)',   landmark:'No. 179'},
        {name:'Amer',                             landmark:'No. 180'},
        {name:'Jal Mahal',                        landmark:'No. 177'},
        {name:'SBI (Vaishali Nagar)',             landmark:'No. 455'},
        {name:'Global Heart Hospital (Vaishali Nagar)', landmark:'No. 458'},
        {name:'Ghandhi Path',                     landmark:'No. 461'},
        {name:'Nursery Circle',                   landmark:'No. 463'},
        {name:'Gandhi Path Mode',                 landmark:'No. 465'},
        {name:'Akshardham Chouraha (Vaishali Nagar)', landmark:'No. 468'},
        {name:'Gupta Store',                      landmark:'No. 471'},
        {name:'Vijay Gate (Queens Road)',         landmark:'No. 472'},
        {name:'National Handloom',                landmark:'No. 476'},
        {name:'Amarpali Circle',                  landmark:'No. 478'},
        {name:'Bajari Mandi (Vaishali Nagar)',    landmark:'No. 479'},
        {name:'Kanakpura (Sirsi Road)',           landmark:'No. 481'},
        {name:'Sirsi Mode',                       landmark:'No. 483'},
        {name:'Hathoj Tiraha (Sirsi Road)',       landmark:'No. 487'},
        {name:'Bindayaka Petrol Pump (Sirsi Road)',landmark:'No. 488'},
        {name:'21 No. Bus Stand',                 landmark:'No. 485'},
        {name:'Panchayawala',                     landmark:'No. 482'},
        {name:'Jaswant Nagar (Khatipura)',        landmark:'No. 484'},
        {name:'Khatipura Mode',                   landmark:'No. 601'},
        {name:'Khatipura Saras Dairy',            landmark:'No. 608'},
        {name:'Shani Mandir (Khatipura)',         landmark:'No. 615'},
        {name:'Khatipura Pulia',                  landmark:'No. 617'},
        {name:'Jodhpur Misthan Bhandar (Jhotwara)',landmark:'No. 620'},
        {name:'Lata Cinema',                      landmark:'No. 623'},
        {name:'Medical Centre (Jhotwara)',        landmark:'No. 624'},
        {name:'Kanta',                            landmark:'No. 625'},
        {name:'Pankha',                           landmark:'No. 626'},
        {name:'Khirani Phatak',                   landmark:'No. 630'},
        {name:'Shanskar School (Khirni Phatak)',  landmark:'No. 631'},
        {name:'Bharat Petrol Pump (Jhotwara)',    landmark:'No. 632'},
        {name:'Boring Circle',                    landmark:'No. 636'},
        {name:'Joshi Marg',                       landmark:'No. 638'},
        {name:'Rawan Gate',                       landmark:'No. 642'},
        {name:'Govindam Tower',                   landmark:'No. 646'},
        {name:'Shekhawat Marg',                   landmark:'No. 648'},
        {name:'Govindpura',                       landmark:'No. 652'},
        {name:'Hathoj Bus Stand (Kalwar Road)',   landmark:'No. 658'},
        {name:'Royal City (Kalwar Road)',         landmark:'No. 656'},
        {name:'Mahatma Gandhi Govt. School, Machwa', landmark:'No. 657'},
        {name:'Khandaka Hospital',                landmark:'No. 655'},
        {name:'Niwaru Puliya',                    landmark:'No. 657'},
        {name:'Nagal Puliya',                     landmark:'No. 659'},
        {name:'Vaidh Ji Ka Chauraha (Niwaru Road)',landmark:'No. 661'},
        {name:'34 No. Bus Stand Niwaru Old',      landmark:'No. 664'},
        {name:'Army Gate (Lal Chandpura-Niwaru)', landmark:'No. 663'},
        {name:'Niwaru Bus Stand',                 landmark:'No. 663'},
        {name:'Pani Pech',                        landmark:'No. 834'},
        {name:'Ambabari',                         landmark:'No. 838'},
        {name:'Bhawani Niketan School',           landmark:'No. 840'},
        {name:'Khaitan Hospital',                 landmark:'No. 844'},
        {name:'Harmada Thana',                    landmark:'No. 845'},
        {name:'Nindar Mode',                      landmark:'No. 846'},
        {name:'Todi Mode',                        landmark:'No. 849'},
        {name:'Rajawas Bus Stand (Sikar Road)',   landmark:'No. 850'},
        {name:'Jodla Power House',                landmark:'No. 847'},
        {name:'VKI No. 14',                       landmark:'No. 848'},
        {name:'Shastri Nagar-Petrol Pump',        landmark:'No. 852'},
        {name:'Subhash Colony',                   landmark:'No. 854'},
        {name:'Science Park',                     landmark:'No. 856'},
        {name:'Kanvatiya Circle',                 landmark:'No. 860'},
        {name:'Biyani College',                   landmark:'No. 865'},
        {name:'Mandir Mode',                      landmark:'No. 866'},
        {name:'Hari Nagar (Shastri Nagar)',       landmark:'No. 871'},
        {name:'Vidhyadhar Nagar Sec. 2',          landmark:'No. 877'},
        {name:'Vidhyadhar Nagar Sec. 5,6,7,10',  landmark:'No. 880'},
        {name:'Alka Cinema',                      landmark:'No. 881'},
        {name:'Agarasen Tower',                   landmark:'No. 883'},
        {name:'Murlipura Main Road',              landmark:'No. 885'},
        {name:'Kediya Palace',                    landmark:'No. 887'},
        {name:'Benad Phatak',                     landmark:'No. 893'},
        {name:'Sitavali Phatak',                  landmark:'No. 891'},
        {name:'Nadi ka Phatak',                   landmark:'No. 890'},
        {name:'Dadi ka Phatak',                   landmark:'No. 889'},
        {name:'Vaidh Ji ka Chouraha (M)',         landmark:'No. 892'},
        {name:'VKI Road No. 01 & 05',            landmark:'No. 894'},
        {name:'Kiran Palace',                     landmark:'No. 920'},
        {name:'Tagore Nagar (Ajmer Road)',        landmark:'No. 922'},
        {name:'Purani Chugi (Ajmer Road)',        landmark:'No. 925'},
        {name:'Gehlot Ka Bungalow',               landmark:'No. 930'},
        {name:'DCM',                              landmark:'No. 935'},
        {name:'Bhankrota-200 Feet Byepass',       landmark:'No. 940'},
        {name:'Heerapura',                        landmark:'No. 945'},
        {name:'Kamla Nehru Nagar',                landmark:'No. 950'},
        {name:'Bhankrota Bus Stand',              landmark:'No. 951'},
        {name:'Mahapura Mode',                    landmark:'No. 952'},
        {name:'Ram Chandrapura (Ajmer Road)',     landmark:'No. 953'},
        {name:'Poornima University',              landmark:'Main Gate'},
      ]
    },
    {
      routeNo: 'R-COMMON',
      routeName: 'Common / Single Route – Poornima University',
      annualFee: null,
      morning: '12:30 PM', evening: '05:30 PM',
      driver: 'Vishnu Kumar Yadav (Transport Officer)', driverPhone: '9829855516',
      vehicle: 'Poornima University Bus',
      notes: '50% rebate for BBA/B.Com/BVA/BA/B.Sc students. Two buses on this route if demand increases.',
      stops: [
        {name:'India Gate',                       landmark:'No. 101'},
        {name:'Kumbha Gate',                      landmark:'No. 103'},
        {name:'LIC Office',                       landmark:'No. 105'},
        {name:'Pratap Plaza',                     landmark:'No. 109'},
        {name:'Laxmi Sweet',                      landmark:'No. 111'},
        {name:'Gaushala',                         landmark:'No. 113'},
        {name:'Sanagner Thana',                   landmark:'No. 115'},
        {name:'Sitabari',                         landmark:'No. 117'},
        {name:'Durgapura Bus Stand',              landmark:'No. 125'},
        {name:'Gopalpura',                        landmark:'No. 418'},
        {name:'Laxmi Mandir Circle (Tonk Road)', landmark:'No. 137'},
        {name:'Ghandhi Nagar Mode',               landmark:'No. 141'},
        {name:'Sodhani Sweets (TR)',              landmark:'No. 143'},
        {name:'Rambagh Circle',                   landmark:'No. 145'},
        {name:'Narayan Singh Circle',             landmark:'No. 151'},
        {name:'SMS Hospital',                     landmark:'No. 153'},
        {name:'Ajmeri Gate',                      landmark:'No. 157'},
        {name:'Poornima University',              landmark:'Main Gate'},
      ]
    },
  ]);
  console.log('✅ Bus routes seeded — 3 main routes + 1 common route with REAL stop data');

  // ── Timetable ─────────────────────────────────────────────────
  await Timetable.deleteMany({});
  await Timetable.create({
    course:'B.Tech CSE', semester:'5th Semester', section:'A', updatedBy:'Academic Admin',
    slots:[
      {time:'09:00–10:00', monday:'Data Structures',   tuesday:'OS Lab',           wednesday:'DBMS',             thursday:'Computer Networks', friday:'Software Engg',   type:'subject'},
      {time:'10:00–11:00', monday:'Computer Networks', tuesday:'OS Lab',           wednesday:'Computer Networks', thursday:'DBMS',             friday:'Data Structures', type:'subject'},
      {time:'11:00–11:15', monday:'Break',             tuesday:'Break',            wednesday:'Break',             thursday:'Break',            friday:'Break',           type:'break'},
      {time:'11:15–12:15', monday:'DBMS',              tuesday:'Software Engg',    wednesday:'Data Structures',   thursday:'OS',               friday:'DBMS',            type:'subject'},
      {time:'12:15–01:15', monday:'OS',                tuesday:'Computer Networks',wednesday:'Software Engg',     thursday:'Data Structures',  friday:'OS',              type:'subject'},
      {time:'01:15–02:00', monday:'Lunch',             tuesday:'Lunch',            wednesday:'Lunch',             thursday:'Lunch',            friday:'Lunch',           type:'break'},
      {time:'02:00–04:00', monday:'DBMS Lab',          tuesday:'Free',             wednesday:'CN Lab',            thursday:'Free',             friday:'DS Lab',          type:'lab'},
    ]
  });
  console.log('✅ Timetable seeded');

  console.log('\n🎉 Ready! All accounts:');
  console.log('─────────────────────────────────────────────────────────────');
  console.log('🎓 STUDENT          → ID: PU2021CS045   | Pass: student123');
  console.log('📚 ACADEMIC ADMIN   → ID: ACAD001        | Pass: admin123');
  console.log('👕 LAUNDRY ADMIN    → ID: LAUN001         | Pass: laundry123');
  console.log('👑 CHAIR (Vanshaj)  → ID: SC-CHAIR        | Pass: chair123');
  console.log('🤝 CO-CHAIR (Uma)   → ID: SC-COCHAIR1     | Pass: cochair123');
  console.log('🤝 CO-CHAIR (Aaryan)→ ID: SC-COCHAIR2     | Pass: cochair123');
  console.log('🤝 CO-CHAIR (Pranjal)→ ID: SC-COCHAIR3    | Pass: cochair123');
  console.log('🏫 ANY CAPTAIN      → ID: CAP-[SHORTNAME] | Pass: captain123');
  console.log('🤝 VICE CAPTAIN     → ID: VC-[SHORTNAME]  | Pass: captain123');
  console.log('   e.g. VC-PANDORA, VC-HACKELITE, VC-NSS ...');
  console.log('   e.g. CAP-EHC, CAP-HACKELITE, CAP-OSC, CAP-DANCE ...');
  console.log('─────────────────────────────────────────────────────────────');
  process.exit(0);
}

seed().catch(err => { console.error('❌ Seed error:', err); process.exit(1); });
